In [1]:
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [4]:
questURL = 'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=1\
           &max_rnk=1\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'
Quest = requests.get(questURL).json()
Quest

{'StudyFieldsResponse': {'APIVrs': '1.01.02',
  'DataVrs': '2020:07:24 00:13:26.663',
  'Expression': 'covid 19',
  'NStudiesAvail': 346767,
  'NStudiesFound': 2874,
  'MinRank': 1,
  'MaxRank': 1,
  'NStudiesReturned': 1,
  'FieldList': ['NCTId',
   'BriefTitle',
   'StatusVerifiedDate',
   'CompletionDate',
   'OrgFullName',
   'OrgClass',
   'Keyword',
   'LocationCity',
   'LocationCountry',
   'EnrollmentCount',
   'StdAge',
   'Gender'],
  'StudyFields': [{'Rank': 1,
    'NCTId': ['NCT04395482'],
    'BriefTitle': ['Lung CT Scan Analysis of SARS-CoV2 Induced Lung Injury'],
    'StatusVerifiedDate': ['May 2020'],
    'CompletionDate': ['October 15, 2020'],
    'OrgFullName': ['University of Milano Bicocca'],
    'OrgClass': ['OTHER'],
    'Keyword': ['Lung injury', 'sars-covid-2', 'coronavirus infection'],
    'LocationCity': ['Bergamo',
     'Bergamo',
     'Ferrara',
     'Lecco',
     'Melzo',
     'Monza',
     'Rimini',
     'San Marino'],
    'LocationCountry': ['Italy',
     'Italy',
     'Italy',
     'Italy',
     'Italy',
     'Italy',
     'Italy',
     'San Marino'],
    'EnrollmentCount': ['500'],
    'StdAge': ['Adult', 'Older Adult'],
    'Gender': ['All']}]}}

In [11]:
limit1 = Quest['StudyFieldsResponse']['NStudiesFound'] #make sure we don't ask for results outside of the scope of our query
limit1

2874

In [12]:
# Query the api in packets of 1000 then merge into a single dataframe

tempURL1 = 'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=1\
           &max_rnk=1000\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'   
tempL1 = requests.get(tempURL1).json()

tempURL2 = 'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=1001\
           &max_rnk=2000\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'
tempL2 = requests.get(tempURL2).json()                                                             

tempURL3 = f'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=2001\
           &max_rnk={limit1}\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'
tempL3 = requests.get(tempURL3).json()

Q1_tempL1 = tempL1['StudyFieldsResponse']['StudyFields']
Q1_tempL2 = tempL2['StudyFieldsResponse']['StudyFields']
Q1_tempL3 = tempL3['StudyFieldsResponse']['StudyFields']

In [13]:
Q1_tempDF1 = pd.DataFrame(Q1_tempL1)
Q1_tempDF2 = pd.DataFrame(Q1_tempL2)
Q1_tempDF3 = pd.DataFrame(Q1_tempL3)

In [14]:

#returns single list of col values from all 3 temp DF's 

def unListItems(col):
    lst_1 = [' ']*len(Q1_tempDF1[col])  # create empty list the length of 'Q1_tempDF1[col]'
    i = 0
    while i < len(Q1_tempDF1[col]):
        if len(Q1_tempDF1[col][i])==0:
            lst_1[i] = None
        else:
            lst_1[i] = Q1_tempDF1[col][i][0]
        i += 1
    lst_2 = [' ']*len(Q1_tempDF2[col])
    i = 0
    while i < len(Q1_tempDF2[col]):
        if len(Q1_tempDF2[col][i])==0:
            lst_2[i] = None
        else:
            lst_2[i] = Q1_tempDF2[col][i][0]
        i += 1      
    lst_3 = [' ']*len(Q1_tempDF3[col])
    i = 0
    while i < len(Q1_tempDF3[col]):
        if len(Q1_tempDF3[col][i])==0:
            lst_3[i] = None
        else:
            lst_3[i] = Q1_tempDF3[col][i][0]
        i += 1
    LIST = lst_1 + lst_2 + lst_3
    return LIST

In [15]:
Q1_tempDF3

,Rank,NCTId,BriefTitle,StatusVerifiedDate,CompletionDate,OrgFullName,OrgClass,Keyword,LocationCity,LocationCountry,EnrollmentCount,StdAge,Gender
0,2001,[NCT04412330],[Optimizing Outcomes With Physical Therapy Tre...,[June 2020],"[May 1, 2021]",[University of Kentucky],[OTHER],[],[Lexington],[United States],[20],"[Adult, Older Adult]",[All]
1,2002,[NCT04372680],[WeanINg From Mechanical Ventilation for ARDS ...,[April 2020],"[September 22, 2020]","[University Hospital, Toulouse]",[OTHER],"[COVID-19,, ARDS, Mechanical ventilation, Lung...","[Limoges, Toulouse]","[France, France]",[200],"[Adult, Older Adult]",[All]
2,2003,[NCT04397172],[Intensive Care Associated Complications and O...,[May 2020],[December 2021],"[University Hospital Inselspital, Berne]",[OTHER],"[Corona, SARS-CoV2, ARDS, PICS]",[Bern],[Switzerland],[50],"[Adult, Older Adult]",[All]
3,2004,[NCT04447534],[Zinc With Chloroquine/Hydroxychloroquine in T...,[June 2020],"[August 1, 2020]",[Tanta University],[OTHER],[],[Tanta],[Egypt],[200],"[Adult, Older Adult]",[All]
4,2005,[NCT04285190],[The Effect of T89 on Improving Oxygen Saturat...,[March 2020],"[April 20, 2020]","[Tasly Pharmaceuticals, Inc.]",[INDUSTRY],[COVID-19],[],[],[0],"[Adult, Older Adult]",[All]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,2870,[NCT03728257],[Lung Transplant G0 (LTGO): Improving Self-Man...,[June 2020],"[April 8, 2022]",[University of Pittsburgh],[OTHER],[],[Pittsburgh],[United States],[112],"[Adult, Older Adult]",[All]
870,2871,[NCT03823469],[Evaluating the Impact of a Culinary Coaching ...,[May 2020],[February 2022],[Spaulding Rehabilitation Hospital],[OTHER],"[Home cooking, Telemedicine, Nutrition, Health...","[Charlestown, Ramat Gan]","[United States, Israel]",[78],"[Adult, Older Adult]",[All]
871,2872,[NCT04429061],[Reaching 90 90 90 in Adolescents in Zambia: U...,[June 2020],"[June 30, 2023]",[University of Alabama at Birmingham],[OTHER],"[Adolescents, Zambia, Football]",[Lusaka],[Zambia],[3200],"[Child, Adult, Older Adult]",[Female]
872,2873,[NCT03922334],[Navigating New Motherhood 2],[June 2020],[December 2024],[Northwestern University],[OTHER],[],[Chicago],[United States],[400],"[Child, Adult]",[Female]
873,2874,[NCT04180709],[CBT to Reduce Insomnia and Improve Social Rec...,[June 2020],"[November 30, 2022]",[University of Cambridge],[OTHER],"[Cognition, Social Recovery, Immunopsychiatry,...",[Cambridge],[United Kingdom],[44],"[Adult, Older Adult]",[All]

In [16]:
#retrive unListed Items, populate Query1 DataFrame with query results from id, title, and date keys

ID = unListItems('NCTId')
Title = unListItems('BriefTitle')
VerifiedDate = unListItems('StatusVerifiedDate')
CompletionDate = unListItems('CompletionDate')
OrgFullName = unListItems('OrgFullName')
OrgClass = unListItems('OrgClass')
QueryType = ['covid 19']*len(ID)
Country = unListItems('LocationCountry')
City = unListItems('LocationCity')
Participants = unListItems("EnrollmentCount")
Age_Groups = unListItems("StdAge")
Gender = unListItems("Gender")

DF_Q1 = pd.DataFrame()
DF_Q1.insert(0, 'ID', ID)
DF_Q1.insert(1, 'Title', Title)
DF_Q1.insert(2, 'Date Verified', VerifiedDate)
DF_Q1.insert(3, 'Completion Date', CompletionDate)
DF_Q1.insert(4, 'Organization', OrgFullName)
DF_Q1.insert(5, 'Organization Class', OrgClass)
DF_Q1.insert(6, 'Country', Country)
DF_Q1.insert(7, 'City', City)
DF_Q1.insert(8, 'Participants', Participants)
DF_Q1.insert(9, 'Age Groups', Age_Groups)
DF_Q1.insert(10, 'Gender', Gender)

In [17]:
groupID = DF_Q1.groupby('ID')

In [18]:
df = pd.DataFrame(groupID.count())

In [19]:
DF_Q1.loc[DF_Q1['ID']=='NCT04330144']

,ID,Title,Date Verified,Completion Date,Organization,Organization Class,Country,City,Participants,Age Groups,Gender
907,NCT04330144,Hydroxychloroquine as Post Exposure Prophylaxi...,March 2020,"March 30, 2022",Gangnam Severance Hospital,OTHER,None,None,2486,Adult,All

In [20]:
df = df.loc[df['Title']>1]

In [21]:
dupeList = []
for i in df.index:
    dupeList.append(i)
print(dupeList)

['NCT04313127', 'NCT04324606', 'NCT04324866', 'NCT04332016', 'NCT04335084', 'NCT04335188', 'NCT04336761', 'NCT04342884', 'NCT04344379', 'NCT04344548', 'NCT04345601', 'NCT04345848', 'NCT04347512', 'NCT04349618', 'NCT04350086', 'NCT04352959', 'NCT04353271', 'NCT04354428', 'NCT04355429', 'NCT04355494', 'NCT04358588', 'NCT04360759', 'NCT04362969', 'NCT04363541', 'NCT04364737', 'NCT04366154', 'NCT04366167', 'NCT04369469', 'NCT04369794', 'NCT04370119', 'NCT04371354', 'NCT04371471', 'NCT04372680', 'NCT04373811', 'NCT04374461', 'NCT04375397', 'NCT04375670', 'NCT04377503', 'NCT04379297', 'NCT04379544', 'NCT04380779', 'NCT04382131', 'NCT04382196', 'NCT04382391', 'NCT04384731', 'NCT04385121', 'NCT04389671', 'NCT04395768', 'NCT04401202', 'NCT04401527', 'NCT04402905', 'NCT04403100', 'NCT04403438', 'NCT04403906', 'NCT04407273', 'NCT04408040', 'NCT04408365', 'NCT04409327', 'NCT04411511', 'NCT04412018', 'NCT04414410', 'NCT04416308', 'NCT04416399', 'NCT04421391', 'NCT04424901', 'NCT04430062', 'NCT04431869', 'NCT04432350', 'NCT04432922', 'NCT04433949', 'NCT04434157', 'NCT04435314', 'NCT04442087', 'NCT04443140', 'NCT04444531', 'NCT04444609', 'NCT04445220', 'NCT04445246', 'NCT04445285', 'NCT04446169', 'NCT04448782', 'NCT04451317', 'NCT04452422', 'NCT04452487', 'NCT04456010', 'NCT04456426', 'NCT04456556', 'NCT04459689', 'NCT04462120', 'NCT04463004', 'NCT04468009', 'NCT04469634', 'NCT04473547', 'NCT04477993', 'NCT04479150']

In [22]:
query = 'coronavirus'
quest2URL = f'http://ClinicalTrials.gov/api/query/study_fields?expr={query}\
           &min_rnk=1\
           &max_rnk=1\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'
Quest2 = requests.get(quest2URL).json()
Quest2

{'StudyFieldsResponse': {'APIVrs': '1.01.02',
  'DataVrs': '2020:07:24 00:13:26.663',
  'Expression': 'coronavirus',
  'NStudiesAvail': 346767,
  'NStudiesFound': 1458,
  'MinRank': 1,
  'MaxRank': 1,
  'NStudiesReturned': 1,
  'FieldList': ['NCTId',
   'BriefTitle',
   'StatusVerifiedDate',
   'CompletionDate',
   'OrgFullName',
   'OrgClass',
   'Keyword',
   'LocationCity',
   'LocationCountry',
   'EnrollmentCount',
   'StdAge',
   'Gender'],
  'StudyFields': [{'Rank': 1,
    'NCTId': ['NCT04279795'],
    'BriefTitle': ['Detection of 2019 Novel Coronavirus in Multiple Organ System and Its Relationship With Clinical Manifestations'],
    'StatusVerifiedDate': ['February 2020'],
    'CompletionDate': ['February 28, 2021'],
    'OrgFullName': ['Third Affiliated Hospital, Sun Yat-Sen University'],
    'OrgClass': ['OTHER'],
    'Keyword': ['2019 Novel Coronavirus'],
    'LocationCity': ['Guangzhou'],
    'LocationCountry': ['China'],
    'EnrollmentCount': ['20'],
    'StdAge': ['Child', 'Adult', 'Older Adult'],
    'Gender': ['All']}]}}

In [23]:

limit2 = Quest2['StudyFieldsResponse']['NStudiesFound'] #make sure we don't ask for results outside of the scope of our query
limit2

1458

In [24]:
# Query the api in packets of 1000 then merge into a single dataframe
tempURL1 = 'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=1\
           &max_rnk=1000\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'   

tempL1 = requests.get(tempURL1).json()

tempURL2 = f'http://ClinicalTrials.gov/api/query/study_fields?expr=covid+19\
           &min_rnk=1001\
           &max_rnk={limit2}\
           &fields=\
               NCTId,\
               BriefTitle,\
               StatusVerifiedDate,\
               CompletionDate,\
               OrgFullName,\
               OrgClass,\
               keyword,\
               LocationCity,\
               LocationCountry,\
               EnrollmentCount,\
               STDAge,\
               Gender\
           &fmt=JSON'
tempL2 = requests.get(tempURL2).json()                                                             

Q2_tempL1 = tempL1['StudyFieldsResponse']['StudyFields']
Q2_tempL2 = tempL2['StudyFieldsResponse']['StudyFields']

In [25]:

Q2_tempDF1 = pd.DataFrame(Q2_tempL1)
Q2_tempDF2 = pd.DataFrame(Q2_tempL2)

In [27]:

def unListItemsQ2(col):
    lst_1 = [' ']*len(Q2_tempDF1[col])  # create empty list the length of 'Q1_tempDF1[col]'
    i = 0
    while i < len(Q2_tempDF1[col]):
        if len(Q2_tempDF1[col][i])==0:
            lst_1[i] = None
        else:
            lst_1[i] = Q2_tempDF1[col][i][0]
        i += 1
    lst_2 = [' ']*len(Q2_tempDF2[col])
    i = 0
    while i < len(Q2_tempDF2[col]):
        if len(Q2_tempDF2[col][i])==0:
            lst_2[i] = None
        else:
            lst_2[i] = Q2_tempDF2[col][i][0]
        i += 1      
    LIST = lst_1 + lst_2
    return LIST

In [28]:
#retrive unListed Items, populate Query1 DataFrame with query results from id, title, and date keys

ID = unListItemsQ2('NCTId')
Title = unListItemsQ2('BriefTitle')
VerifiedDate = unListItemsQ2('StatusVerifiedDate')
CompletionDate = unListItemsQ2('CompletionDate')
OrgFullName = unListItemsQ2('OrgFullName')
OrgClass = unListItemsQ2('OrgClass')
QueryType = ['coronavirus']*len(ID)
Country = unListItemsQ2('LocationCountry')
City = unListItemsQ2('LocationCity')
Participants = unListItemsQ2("EnrollmentCount")
Age_Groups = unListItemsQ2("StdAge")
Gender = unListItemsQ2("Gender")


DF_Q2 = pd.DataFrame()
DF_Q2.insert(0, 'ID', ID)
DF_Q2.insert(1, 'Title', Title)
DF_Q2.insert(2, 'Date Verified', VerifiedDate)
DF_Q2.insert(3, 'Completion Date', CompletionDate)
DF_Q2.insert(4, 'Organization', OrgFullName)
DF_Q2.insert(5, 'Organization Class', OrgClass)
DF_Q2.insert(6, 'Country', Country)
DF_Q2.insert(7, 'City', City)
DF_Q2.insert(8, 'Participants', Participants)
DF_Q2.insert(9, 'Age Groups', Age_Groups)
DF_Q2.insert(10, 'Gender', Gender)

In [29]:
DF_QQ = pd.concat([DF_Q1,DF_Q2], ignore_index=True)
DF_QQ = DF_QQ.drop_duplicates()
DF_QQ.set_index('ID', inplace=True)
DF_QQ

,Title,Date Verified,Completion Date,Organization,Organization Class,Country,City,Participants,Age Groups,Gender
ID,,,,,,,,,,
NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,May 2020,"October 15, 2020",University of Milano Bicocca,OTHER,Italy,Bergamo,500,Adult,All
NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,June 2020,May 2021,Centre Hospitalier Régional d'Orléans,OTHER,France,Orléans,50,Adult,Female
NCT04476940,COVID-19 Breastfeeding Guideline for African-A...,July 2020,June 2022,Meharry Medical College,OTHER,United States,Nashville,200,Adult,Female
NCT04412265,Frailty in Elderly Patients With COVID-19,June 2020,"March 1, 2021",University of Milano Bicocca,OTHER,Italy,Monza,300,Adult,All
NCT04427332,Smell and Taste Disorders in COVID-19 Patients,June 2020,"September 30, 2020",University of Milano Bicocca,OTHER,Italy,Monza,500,Adult,All
...,...,...,...,...,...,...,...,...,...,...
NCT03728257,Lung Transplant G0 (LTGO): Improving Self-Mana...,June 2020,"April 8, 2022",University of Pittsburgh,OTHER,United States,Pittsburgh,112,Adult,All
NCT03823469,Evaluating the Impact of a Culinary Coaching T...,May 2020,February 2022,Spaulding Rehabilitation Hospital,OTHER,United States,Charlestown,78,Adult,All
NCT04429061,Reaching 90 90 90 in Adolescents in Zambia: Us...,June 2020,"June 30, 2023",University of Alabama at Birmingham,OTHER,Zambia,Lusaka,3200,Child,Female
NCT03922334,Navigating New Motherhood 2,June 2020,December 2024,Northwestern University,OTHER,United States,Chicago,400,Child,Female
NCT04180709,CBT to Reduce Insomnia and Improve Social Reco...,June 2020,"November 30, 2022",University of Cambridge,OTHER,United Kingdom,Cambridge,44,Adult,All

In [33]:
group_gender = DF_QQ.groupby("Gender")["Title"].count()
group_gender

Gender
All       2686
Female      69
Male        19
Name: Title, dtype: int64

In [34]:
group_age = DF_QQ.groupby("Age Groups")["Title"].count()
group_age

Age Groups
Adult          2241
Child           504
Older Adult      34
Name: Title, dtype: int64

In [35]:
bins = [0, 100, 250, 500, 1000, 2500, 5000, 10000, 50000, 100000]
DF_QQ['binned'] = pd.cut(DF_QQ['Participants'], bins)
DF_QQ

TypeError: '<' not supported between instances of 'int' and 'str'

In [36]:
DF_QQ.dtypes

Title                 object
Date Verified         object
Completion Date       object
Organization          object
Organization Class    object
Country               object
City                  object
Participants          object
Age Groups            object
Gender                object
dtype: object

In [37]:
DF_QQ["Participants"] = pd.to_numeric(DF_QQ["Participants"])

In [38]:
DF_QQ.dtypes

Title                  object
Date Verified          object
Completion Date        object
Organization           object
Organization Class     object
Country                object
City                   object
Participants          float64
Age Groups             object
Gender                 object
dtype: object

In [46]:
bins = [0, 100, 250, 500, 1000, 2500, 5000, 10000, 50000, 100000, 1000000000]
DF_QQ['binned'] = pd.cut(DF_QQ['Participants'], bins)
DF_QQ

,Title,Date Verified,Completion Date,Organization,Organization Class,Country,City,Participants,Age Groups,Gender,binned
ID,,,,,,,,,,,
NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,May 2020,"October 15, 2020",University of Milano Bicocca,OTHER,Italy,Bergamo,500.0,Adult,All,"(250, 500]"
NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,June 2020,May 2021,Centre Hospitalier Régional d'Orléans,OTHER,France,Orléans,50.0,Adult,Female,"(0, 100]"
NCT04476940,COVID-19 Breastfeeding Guideline for African-A...,July 2020,June 2022,Meharry Medical College,OTHER,United States,Nashville,200.0,Adult,Female,"(100, 250]"
NCT04412265,Frailty in Elderly Patients With COVID-19,June 2020,"March 1, 2021",University of Milano Bicocca,OTHER,Italy,Monza,300.0,Adult,All,"(250, 500]"
NCT04427332,Smell and Taste Disorders in COVID-19 Patients,June 2020,"September 30, 2020",University of Milano Bicocca,OTHER,Italy,Monza,500.0,Adult,All,"(250, 500]"
...,...,...,...,...,...,...,...,...,...,...,...
NCT03728257,Lung Transplant G0 (LTGO): Improving Self-Mana...,June 2020,"April 8, 2022",University of Pittsburgh,OTHER,United States,Pittsburgh,112.0,Adult,All,"(100, 250]"
NCT03823469,Evaluating the Impact of a Culinary Coaching T...,May 2020,February 2022,Spaulding Rehabilitation Hospital,OTHER,United States,Charlestown,78.0,Adult,All,"(0, 100]"
NCT04429061,Reaching 90 90 90 in Adolescents in Zambia: Us...,June 2020,"June 30, 2023",University of Alabama at Birmingham,OTHER,Zambia,Lusaka,3200.0,Child,Female,"(2500, 5000]"
NCT03922334,Navigating New Motherhood 2,June 2020,December 2024,Northwestern University,OTHER,United States,Chicago,400.0,Child,Female,"(250, 500]"
NCT04180709,CBT to Reduce Insomnia and Improve Social Reco...,June 2020,"November 30, 2022",University of Cambridge,OTHER,United Kingdom,Cambridge,44.0,Adult,All,"(0, 100]"

In [47]:
group_participants = DF_QQ.groupby("binned")["Title"].count()
group_participants

binned
(0, 100]                1074
(100, 250]               544
(250, 500]               419
(500, 1000]              284
(1000, 2500]             180
(2500, 5000]              92
(5000, 10000]             55
(10000, 50000]            52
(50000, 100000]           12
(100000, 1000000000]      21
Name: Title, dtype: int64

In [55]:
DF_QQ_List1 = pd.concat([Q2_tempDF1, Q2_tempDF2, Q1_tempDF1, Q1_tempDF2, Q1_tempDF3], ignore_index=True)
DF_QQ_List1 = DF_QQ_List1.drop_duplicates()
DF_QQ_List1

TypeError: unhashable type: 'list'

In [52]:
Q2_tempDF1

,Rank,NCTId,BriefTitle,StatusVerifiedDate,CompletionDate,OrgFullName,OrgClass,Keyword,LocationCity,LocationCountry,EnrollmentCount,StdAge,Gender
0,1,[NCT04395482],[Lung CT Scan Analysis of SARS-CoV2 Induced Lu...,[May 2020],"[October 15, 2020]",[University of Milano Bicocca],[OTHER],"[Lung injury, sars-covid-2, coronavirus infect...","[Bergamo, Bergamo, Ferrara, Lecco, Melzo, Monz...","[Italy, Italy, Italy, Italy, Italy, Italy, Ita...",[500],"[Adult, Older Adult]",[All]
1,2,[NCT04395924],[Maternal-foetal Transmission of SARS-Cov-2],[June 2020],[May 2021],[Centre Hospitalier Régional d'Orléans],[OTHER],"[Pregnancy, RT-PCR-COVID-19, SARS-CoV 2 serolo...",[Orléans],[France],[50],[Adult],[Female]
2,3,[NCT04476940],[COVID-19 Breastfeeding Guideline for African-...,[July 2020],[June 2022],[Meharry Medical College],[OTHER],"[COVID-19, Exclusive Breastfeeding, Breastfeed...",[Nashville],[United States],[200],[Adult],[Female]
3,4,[NCT04412265],[Frailty in Elderly Patients With COVID-19],[June 2020],"[March 1, 2021]",[University of Milano Bicocca],[OTHER],"[Coronavirus, sars-covid-2, coronavirus infect...",[Monza],[Italy],[300],"[Adult, Older Adult]",[All]
4,5,[NCT04427332],[Smell and Taste Disorders in COVID-19 Patients],[June 2020],"[September 30, 2020]",[University of Milano Bicocca],[OTHER],"[Coronavirus, sars-covid-2, coronavirus infect...",[Monza],[Italy],[500],"[Adult, Older Adult]",[All]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,[NCT04391920],[Registry of CytoSorb Therapy in COVID-19 ICU ...,[May 2020],[August 2021],"[CytoSorbents, Inc]",[INDUSTRY],[],[],[],[1000],"[Adult, Older Adult]",[All]
996,997,[NCT04431869],[In-Utero Vascular Accidents in Neonates From ...,[June 2020],[July 2022],"[University of Colorado, Denver]",[OTHER],[],[Aurora],[United States],[200],"[Adult, Older Adult]",[All]
997,998,[NCT04466670],[Hemostasis in COVID-19: an Adaptive Clinical ...,[July 2020],"[April 30, 2021]",[University of Sao Paulo General Hospital],[OTHER],"[SARS-CoV-2, Thrombosis, Coagulopathy, Anticoa...",[Sao Paulo],[Brazil],[310],"[Adult, Older Adult]",[All]
998,999,[NCT04402905],[Observational Study in Diagnosed Patients COV...,[May 2020],"[August 15, 2020]",[Centre de Recherches et d'Etude sur la Pathol...,[OTHER],[],[Paris],[France],[450],"[Adult, Older Adult]",[All]
999,1000,[NCT04348240],[Transmissibility and Viral Load of SARS-CoV-2...,"[May 18, 2020]","[July 1, 2021]",[National Institutes of Health Clinical Center...,[NIH],"[Saliva, Coronavirus, SARS-CoV-2, Symptoms, CO...",[Bethesda],[United States],[60],"[Adult, Older Adult]",[All]

In [58]:
c.dtypes

Rank                   int64
NCTId                 object
BriefTitle            object
StatusVerifiedDate    object
CompletionDate        object
OrgFullName           object
OrgClass              object
Keyword               object
LocationCity          object
LocationCountry       object
EnrollmentCount       object
StdAge                object
Gender                object
dtype: object

In [61]:
Q2_tempDF1['StdAge'].map(type)

0      <class 'list'>
1      <class 'list'>
2      <class 'list'>
3      <class 'list'>
4      <class 'list'>
            ...
995    <class 'list'>
996    <class 'list'>
997    <class 'list'>
998    <class 'list'>
999    <class 'list'>
Name: StdAge, Length: 1000, dtype: object

In [ ]:
df['ABC'].map(type)

In [ ]:
Q2_tempDF1[]